version: '3.8'
services:
  node-app:
    build:
      context: ./node-be
      dockerfile: dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - fastapi-app

  fastapi-app:
    build:
      context: ./py-be
      dockerfile: dockerfile
    ports:
      - "8004:8004"

  react-app:
    build:
      context: ./react-fe
      dockerfile: dockerfile
    ports:
      - "3000:3000"
